In [1]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef

from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df4=pd.read_csv('Cap/Empath_variables.csv', delimiter = ',',encoding='utf-8')
df6=df4.drop(['Username','Time','Body','Subreddit'], axis = 1)
df7=df4.drop(['Username','Time','Body','Subreddit','Depressed'], axis = 1)

In [3]:
decode_map = {0: "NORMAL", 1: "DEPRESSED"}
def decode_sentiment(label):
    return decode_map[int(label)]

df6.Depressed = df6.Depressed.apply(lambda x: decode_sentiment(x))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df7, df6.Depressed, test_size=0.2)

In [5]:
#print("AUC:", roc_auc_score(y_test, y_pred))
#print("Precision:", precision_score(y_test, y_pred))
#print("Recall:", recall_score(y_test, y_pred))
#print("F1 Score:", f1_score(y_test, y_pred))

#from sklearn.metrics import roc_auc_score
#from sklearn.metrics import precision_score
#from sklearn.metrics import recall_score
#from sklearn.metrics import f1_score

In [6]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.51      0.52      0.52      7170
      NORMAL       0.48      0.48      0.48      6739

   micro avg       0.50      0.50      0.50     13909
   macro avg       0.50      0.50      0.50     13909
weighted avg       0.50      0.50      0.50     13909



[[3721 3449]
 [3536 3203]]


0.4978071752102955
0.512746313903817
0.5189679218967922
0.5158383586331184
0.4971304960426237
-0.0057416861279935005


In [7]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.82      0.31      0.45      7170
      NORMAL       0.56      0.93      0.70      6739

   micro avg       0.61      0.61      0.61     13909
   macro avg       0.69      0.62      0.58     13909
weighted avg       0.69      0.61      0.57     13909



[[2247 4923]
 [ 491 6248]]


0.6107556258537638
0.8206720233747261
0.3133891213389121
0.45357287040775135
0.6202648233197009
0.3023174192011863


In [8]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=0).fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.73      0.42      0.53      7170
      NORMAL       0.58      0.83      0.68      6739

   micro avg       0.62      0.62      0.62     13909
   macro avg       0.65      0.63      0.61     13909
weighted avg       0.65      0.62      0.61     13909



[[3017 4153]
 [1117 5622]]


0.6211086346969588
0.7298016448959845
0.4207810320781032
0.533793347487615
0.6275147184429691
0.27887141403465227


In [9]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, max_iter=5, random_state=42).fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

   DEPRESSED       0.80      0.36      0.50      7170
      NORMAL       0.57      0.91      0.70      6739

   micro avg       0.62      0.62      0.62     13909
   macro avg       0.69      0.63      0.60     13909
weighted avg       0.69      0.62      0.59     13909



[[2567 4603]
 [ 623 6116]]


0.6242720540657128
0.8047021943573668
0.35801952580195257
0.4955598455598455
0.632786287607906
0.3156952546786396


In [10]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss='log', penalty='l2',alpha=1e-3, max_iter=5, random_state=42).fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

   DEPRESSED       0.74      0.46      0.57      7170
      NORMAL       0.59      0.82      0.69      6739

   micro avg       0.64      0.64      0.64     13909
   macro avg       0.66      0.64      0.63     13909
weighted avg       0.67      0.64      0.63     13909



[[3323 3847]
 [1190 5549]]


0.6378603781724064
0.7363173055617106
0.46345885634588563
0.568860737824189
0.6434373967142695
0.3062284423965557


In [11]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.61      0.68      0.65      7170
      NORMAL       0.62      0.54      0.58      6739

   micro avg       0.61      0.61      0.61     13909
   macro avg       0.61      0.61      0.61     13909
weighted avg       0.61      0.61      0.61     13909



[[4893 2277]
 [3092 3647]]


0.6139909411172622
0.612773951158422
0.6824267782426778
0.6457274826789838
0.6118024972976263
0.2259923930129537


In [12]:
from xgboost import XGBClassifier
clf = XGBClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.72      0.48      0.58      7170
      NORMAL       0.59      0.80      0.68      6739

   micro avg       0.64      0.64      0.64     13909
   macro avg       0.66      0.64      0.63     13909
weighted avg       0.66      0.64      0.63     13909



[[3473 3697]
 [1325 5414]]


0.6389388165935725
0.7238432680283452
0.48437935843793584
0.5803810160427807
0.6438813248637223
0.3025370617579076


In [13]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.71      0.49      0.58      7170
      NORMAL       0.59      0.79      0.68      6739

   micro avg       0.63      0.63      0.63     13909
   macro avg       0.65      0.64      0.63     13909
weighted avg       0.65      0.63      0.63     13909



[[3496 3674]
 [1420 5319]]


0.633762312171975
0.7111472742066721
0.4875871687587169
0.5785206023498263
0.6384367065043027
0.28945451384305126


In [14]:
from sklearn.ensemble import BaggingClassifier
clf = BaggingClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.68      0.57      0.62      7170
      NORMAL       0.61      0.71      0.66      6739

   micro avg       0.64      0.64      0.64     13909
   macro avg       0.64      0.64      0.64     13909
weighted avg       0.64      0.64      0.64     13909



[[4119 3051]
 [1964 4775]]


0.6394420878567834
0.6771329935886898
0.5744769874476987
0.6215951105410096
0.6415195443248287
0.2851509962200374
