In [1]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef

from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Cap/EmpathVariables_PartsOfSpeech1.csv', delimiter = ',',encoding='utf-8')
df=df.drop(['Body'], axis = 1)
df['count']=1

In [3]:
df6=df.groupby(['Username','Depressed'])['Subreddit'].apply(lambda x:','.join(x)).reset_index(name ='Subreddits')
df6['Subreddits'] = df6['Subreddits'].str.replace('depression,', '')

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df6.Subreddits)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts).toarray()

In [5]:
df2=pd.DataFrame(data=X_train_tfidf)

In [6]:
ddf= df.groupby(['Username','Depressed']).mean()
ddf=ddf.reset_index()

In [7]:
df=pd.concat([ddf, df2], axis=1)
df1=df

In [8]:
df.head()

Username  Depressed  Polarity  Subjectivity  Noun Phrases    CC  \
0          #NAME?          0 -0.001289      0.285775      4.333333  0.00   
1         -Chely-          1 -0.059854      0.449464     12.000000  0.00   
2   -Darth_Revan-          1  0.007500      0.260000      3.000000  0.00   
3  -ExtremeMusic-          0  0.004630      0.322222      2.555556  0.00   
4    -GrapeGrass-          0  0.116529      0.405958     10.800000  0.24   

         CD        DT   EX   FW  ...  8576  8577  8578  8579  8580  8581  \
0  1.000000  0.041667  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   
1  4.000000  0.500000  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   
2  2.000000  0.000000  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   
3  1.333333  0.000000  0.0  0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   
4  2.440000  0.160000  0.0  0.2  ...   0.0   0.0   0.0   0.0   0.0   0.0   

   8582  8583  8584  8585  
0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0  

[5 rows x 8822 columns]

In [9]:
decode_map = {0: "NORMAL", 1: "DEPRESSED"}
def decode_sentiment(label):
    return decode_map[int(label)]

df.Depressed = df.Depressed.apply(lambda x: decode_sentiment(x))
df=df.drop(['Username'], axis = 1)
df=df.drop(['Depressed'], axis = 1)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df, df1.Depressed, test_size=0.2)

In [11]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.56      0.57      0.56       483
      NORMAL       0.48      0.46      0.47       413

   micro avg       0.52      0.52      0.52       896
   macro avg       0.52      0.52      0.52       896
weighted avg       0.52      0.52      0.52       896



[[277 206]
 [221 192]]


0.5234375
0.5562248995983936
0.5734989648033126
0.564729867482161
0.5191950029827701
0.03851328499423988


In [12]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.76      0.80      0.78       483
      NORMAL       0.75      0.70      0.73       413

   micro avg       0.75      0.75      0.75       896
   macro avg       0.75      0.75      0.75       896
weighted avg       0.75      0.75      0.75       896



[[385  98]
 [122 291]]


0.7544642857142857
0.7593688362919132
0.7971014492753623
0.7777777777777778
0.7508509667684318
0.5045632154700126


In [13]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=0).fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.84      0.86      0.85       483
      NORMAL       0.83      0.81      0.82       413

   micro avg       0.84      0.84      0.84       896
   macro avg       0.84      0.84      0.84       896
weighted avg       0.84      0.84      0.84       896



[[416  67]
 [ 78 335]]


0.8381696428571429
0.8421052631578947
0.8612836438923396
0.8515864892528147
0.8362108292100924
0.6739284392379011


In [14]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, max_iter=5, random_state=42).fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

   DEPRESSED       0.94      0.79      0.86       483
      NORMAL       0.79      0.94      0.86       413

   micro avg       0.86      0.86      0.86       896
   macro avg       0.87      0.87      0.86       896
weighted avg       0.87      0.86      0.86       896



[[381 102]
 [ 23 390]]


0.8604910714285714
0.943069306930693
0.7888198757763976
0.8590755355129651
0.8665649015685861
0.7344398479754317


In [15]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss='log', penalty='l2',alpha=1e-3, max_iter=5, random_state=42).fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

   DEPRESSED       0.92      0.83      0.87       483
      NORMAL       0.82      0.91      0.86       413

   micro avg       0.87      0.87      0.87       896
   macro avg       0.87      0.87      0.87       896
weighted avg       0.87      0.87      0.87       896



[[401  82]
 [ 36 377]]


0.8683035714285714
0.9176201372997712
0.8302277432712215
0.8717391304347826
0.8715303365266519
0.7410129649285897


In [16]:
from xgboost import XGBClassifier
clf = XGBClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.96      0.97      0.96       483
      NORMAL       0.97      0.95      0.96       413

   micro avg       0.96      0.96      0.96       896
   macro avg       0.96      0.96      0.96       896
weighted avg       0.96      0.96      0.96       896



[[469  14]
 [ 22 391]]


0.9598214285714286
0.955193482688391
0.9710144927536232
0.9630390143737168
0.9588728638102256
0.9191845266959948


In [17]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.94      0.96      0.95       483
      NORMAL       0.95      0.93      0.94       413

   micro avg       0.95      0.95      0.95       896
   macro avg       0.95      0.95      0.95       896
weighted avg       0.95      0.95      0.95       896



[[463  20]
 [ 27 386]]


0.9475446428571429
0.9448979591836735
0.9585921325051759
0.9516957862281602
0.9466084149208689
0.8944260341524756


In [18]:
from sklearn.ensemble import BaggingClassifier
clf = BaggingClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))
print("\n")
print(metrics.confusion_matrix(y_test, y_pred)) 
print("\n")

y_test1= [0 if x=="NORMAL" else x for x in y_test]
y_test1= [1 if x=="DEPRESSED" else x for x in y_test1]

y_pred= [0 if x=="NORMAL" else x for x in y_pred]
y_pred= [1 if x=="DEPRESSED" else x for x in y_pred]

print(metrics.accuracy_score(y_test1, y_pred))            #Accuracy
print(precision_score(y_test1, y_pred))                   #Precision
print(recall_score(y_test1, y_pred))                      #Recall
print(f1_score(y_test1, y_pred))                          #F1 Score
print(roc_auc_score(y_test1, y_pred))                     #AUC
print(matthews_corrcoef(y_test1, y_pred))                 #MCC

              precision    recall  f1-score   support

   DEPRESSED       0.95      0.96      0.96       483
      NORMAL       0.96      0.94      0.95       413

   micro avg       0.95      0.95      0.95       896
   macro avg       0.95      0.95      0.95       896
weighted avg       0.95      0.95      0.95       896



[[466  17]
 [ 24 389]]


0.9542410714285714
0.9510204081632653
0.9648033126293996
0.9578622816032888
0.9533459662420605
0.907919378896506
